Add ability to show/hide hidden games in all modes
zigurana/EmulationStation pull request #33
Opened 2016-09-22 01:25 UTC by mrnohr

In Kids/Kiosk mode hidden games are not shown. However, I also want to be able to use Full mode, but still hide those hidden games. This change adds a menu option next to the "favorites only" toggle, and then filters the game list accordingly.

<img src="http://cloud.mattnohr.com/0f371N0J402q/Screen%20Shot%202016-09-21%20at%208.19.59%20PM.png" width="400px" />

_Note:_ I also removed some trailing whitespace in the files I touched in an attempt to clean up the code a bit.

2016-09-22 01:51 UTC, vlaminck commented
Yes, please. This is a great feature. Cleanup is always nice, too 💯

2016-09-23 11:28 UTC, zigurana commented
Hi,
While I am not really opposed to adding this, I am having trouble imagining your use-case here.
Let me explain how I see the Full/Kiosk/Kid modes working:
* **Full**, everything is visible. This mode is used when administrating the system, setting up games / adding metadata etc.
* **Kiosk**, config menu items and otherwise explicitly hidden items from game-lists are removed from view. For most of the time, this is the default mode, as normally it's not much use looking at the config items and retropie menu, cluttering up the interface.
* **Kid**, this is the reduced view mode. This is meant to be the locked-down mode, only listing whitelisted items that you explicitly allow in this view.

So now you want to be able to hide items while in the Full view, and that makes me wonder if there are items you are missing in the Kiosk view that you want to keep while still hiding others...

Can you explain what type of items you want to hide, and why you do not want to switch to Kiosk?

2016-09-23 11:39 UTC, zigurana commented on es-app/src/guis/GuiGamelistOptions.cpp
> +	// Toggle: Show hidden
This needs to be in a `if(Settings::getInstance()->getString("UIMode") == "Full")` block, as it does not make sense to show the toggle box in any of the other modes.

2016-09-23 11:48 UTC, zigurana commented on es-app/src/guis/GuiGamelistOptions.cpp
> +	});
after this, you'll need to check if there is anything left to show in the view, see above for the same situation in favorites_only.

I agree, that this is likely not an issue with hidden items, as it is with favorites or kid-only stuff, and really, this shouldnt even be handled in this file.
It should be checked with a specific function call to filedata if we are going to encounter this situation more often.
But untill then, it needs to be checked.

2016-09-23 11:54 UTC, vlaminck commented
I see your point, but I use this version of EmulationStation exclusively for favorites. I don't use Kiosk mode and I don't use Kids mode. I do, however, alter configs and go into the RetroPie menus a lot. I would absolutely love to be able to hide items in Full mode.

I also think that anyone using the Full mode purely as an admin area would understand hidden vs non-hidden and check the "Show Hidden" option. Plus, if an item was hidden in the first place, they likely marked it as hidden for a reason. I don't think that allowing items to be hidden in Full mode will cause any issues for people using it strictly as an admin area. If that were the case I would argue that the ability to only show favorites in the Full mode should be removed for the same reason (but please don't do that).

2016-09-23 11:57 UTC, zigurana requested changes

2016-09-23 12:03 UTC, zigurana commented
@vlaminck 
I understand, thanks for explaining. I see no problem with including this, once you've made the changes needed. I'll pick up the larger design issues at some point (basically, creating a new function to check if a new filter has any valid items left to show).

2016-09-23 12:57 UTC, mrnohr commented on es-app/src/guis/GuiGamelistOptions.cpp
> +	// Toggle: Show hidden
Good point. I'll make the changes

2016-09-26 00:31 UTC, mrnohr commented
I made the updates as recommended by @zigurana. Now this option only shows in "Full" mode and if there are only hidden games (which should be unlikely) and you choose to not show them, it will check and revet that setting back to show them.

2016-09-26 08:47 UTC, zigurana approved these changes

2016-09-26 08:48 UTC, merged

2016-09-26 08:48 UTC, zigurana commented
And done!

2016-09-26 08:49 UTC, zigurana commented
Just want to say, this was my first PR as an owner/maintainer, so thanks!